### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by sysarcher**
Fixes minor typo I hit while following the instructions

### CODE REVIEW

**Review by gvancuts — APPROVED** [review]
Good catch - thanks!

**Review by gvancuts — CHANGES_REQUESTED** [review]
This patch should actually be applied to this file: https://github.com/projectacrn/acrn-hypervisor/blob/master/doc/getting-started/building-from-source.rst.

The HTML output will be re-generated (and published) by @dbkinder once the patch to the original `.rst` file has been merged.

**Comment by sysarcher** [comment]
>This patch should actually be applied to this file: https://github.com/projectacrn/acrn-hypervisor/blob/master/doc/getting-started/building-from-source.rst.

@gvancuts I guess I should close this PR and open up a new one there..

Sorry, I wasn't aware on how this was done. I landed on this repo from projectacrn.github.io directly

**Comment by gvancuts** [comment]
> @gvancuts I guess I should close this PR and open up a new one there..

Yes, that's the best course of action.

> Sorry, I wasn't aware on how this was done. I landed on this repo from projectacrn.github.io directly

No harm done, I appreciate you took the time to create a PR to fix this! If you're curious to have more details on how we develop and generate the project's documentation, here are a couple of links for you:
* https://projectacrn.github.io/latest/tutorials/docbuild.html
* https://projectacrn.github.io/latest/developer-guides/doc_guidelines.html

You don't need to read those before opening up a new PR though ;-)

**Pull request closed without merging**
